export const ADD_FAVOURITE_COMMENT = "ADD_FAVOURITE_COMMENT";
export const REMOVE_FAVOURITE_COMMENT = "REMOVE_FAVOURITE_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENTS = "ADD_COMMENTS";
